<div class="search_part">
    <input type="text">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search">
        <circle cx="11" cy="11" r="8"></circle>
        <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
    </svg>
</div>
<div class="product_card">
    <h2><?= htmlspecialchars($product['name']) ?></h2>
    <div class="product_picture">
        <div class="price_picture">
            <p id="updated_price" data="<?= htmlspecialchars($product['price']) ?>"><?= htmlspecialchars($product['price']) ?></p>
            <p>€</p>
        </div>
    </div>
    <div class="product_action">
        <?php if (isset($_SESSION['id']) && !empty($_SESSION['id'])) : ?>
            <?php if ($bookmark == 0) : ?>
                <button class="bookmark" data-user="<?= $_SESSION['id'] ?>" data-product="<?= $product['p_id'] ?>">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bookmark">
                        <path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"></path>
                    </svg>
                </button>
            <?php else : ?>
                <button class="bookmark" data-user="<?= $_SESSION['id'] ?>" data-product="<?= $product['p_id'] ?>">
                    <svg class="mark" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bookmark">
                        <path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"></path>
                    </svg>
                </button>
            <?php endif; ?>
        <?php endif; ?>
        <div class="select_amount">
            <button class="less">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu">
                    <line x1="3" y1="12" x2="21" y2="12"></line>
                </svg>
            </button>
            <input class="amount" type="number" value="1" min="1" max="10" disabled>
            <button class="more">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus">
                    <line x1="12" y1="5" x2="12" y2="19"></line>
                    <line x1="5" y1="12" x2="19" y2="12"></line>
                </svg>
            </button>
        </div>
        <button>
            <svg class="card" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-cart">
                <circle cx="9" cy="21" r="1"></circle>
                <circle cx="20" cy="21" r="1"></circle>
                <path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path>
            </svg>
        </button>
    </div>
    <div class="product_info">
        <ul>
            <li>type</li>
            <li><?= htmlspecialchars($product['type']) ?></li>
        </ul>
        <ul>
            <li>descriptif</li>
            <li><?= htmlspecialchars($product['description']) ?></li>
        </ul>
        <ul>
            <li>vendeur</li>
            <li><a href="index.php?page=profil&amp;id=<?= $product['id_vendor'] ?>"><?= htmlspecialchars($product['vendor']) ?></a></li>
        </ul>
        <ul>
            <li>prix unitaire</li>
            <li><?= htmlspecialchars($product['price']) ?> €</li>
        </ul>
    </div>
</div>