    <div class="profil_card">
        <div class="profil_card_picture">
            <img src="view/img/pp.png" alt="photo">
        </div>
        <!-- <?php if (isset($_SESSION['id']) && !empty($_SESSION['id'])) : ?>
            <div class="profil_card_info">
                <p><?= $_SESSION['user'] ?></p>
            </div>
        <?php else : ?>

        <?php endif; ?> -->
    </div>
    <p>Produits de </p>
    <div class="article_grid">
        <?php foreach ($product_user as $prod) : ?>
            <a href="">
                <div class="item">
                    <p><?= $prod['name'] ?></p>
                </div>
            </a>
        <?php endforeach; ?>
    </div>